### ISSUE TITLE
Shall 4.4 version be implemented?

### ISSUE THREAD

**Issue by vach** [OpenHFT/TransFIX#20]
I was thinking to use TransFIX for OKCoin and few other exchagnes but thos all use 4.4 version of FIX, is there any plan to implement 4.4?

**Comment by BoundedBuffer** [comment]
Nope - none in the short term. 

But if you update transfix to support 4.4, we are happy to include your pull request.

**Comment by vach** [comment]
I'd love to but i never worked with fix protocol, this was intended to be the first use :)
